// ============================================================
// COMMUNITY BOARD – QUOTES, TIPS, DISCUSSIONS & Q&A DATABASE
// ============================================================
const COMMUNITY_BOARD = {
  // Motivational quotes that rotate daily
  quotes: [
    { text: "“Success is the sum of small efforts, repeated day in and day out.”", author: "Robert Collier" },
    { text: "“Don’t watch the clock; do what it does. Keep going.”", author: "Sam Levenson" },
    { text: "“The expert in anything was once a beginner.”", author: "Helen Hayes" },
    { text: "“Education is the most powerful weapon which you can use to change the world.”", author: "Nelson Mandela" },
    { text: "“Your future is created by what you do today, not tomorrow.”", author: "Robert Kiyosaki" },
    { text: "“It always seems impossible until it’s done.”", author: "Nelson Mandela" },
    { text: "“Strive for progress, not perfection.”", author: "Unknown" },
    { text: "“The beautiful thing about learning is that nobody can take it away from you.”", author: "B.B. King" },
    { text: "“Do something today that your future self will thank you for.”", author: "Unknown" },
    { text: "“You don’t have to be great to start, but you have to start to be great.”", author: "Zig Ziglar" },
    { text: "“Believe you can and you’re halfway there.”", author: "Theodore Roosevelt" },
    { text: "“The only place where success comes before work is in the dictionary.”", author: "Vidal Sassoon" },
    { text: "“The secret of getting ahead is getting started.”", author: "Mark Twain" },
    { text: "“You are never too old to set another goal or to dream a new dream.”", author: "C.S. Lewis" },
    { text: "“The future belongs to those who believe in the beauty of their dreams.”", author: "Eleanor Roosevelt" },
    { text: "“Don’t let what you cannot do interfere with what you can do.”", author: "John Wooden" },
    { text: "“The way to get started is to quit talking and begin doing.”", author: "Walt Disney" },
    { text: "“It does not matter how slowly you go as long as you do not stop.”", author: "Confucius" },
    { text: "“Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.”", author: "Thomas Edison" },
    { text: "“Motivation is what gets you started. Habit is what keeps you going.”", author: "Jim Ryun" },
    { text: "“Success is not final, failure is not fatal: it is the courage to continue that counts.”", author: "Winston Churchill" },
    { text: "“The only way to do great work is to love what you do.”", author: "Steve Jobs" },
    { text: "“If you can dream it, you can do it.”", author: "Walt Disney" },
    { text: "“Act as if what you do makes a difference. It does.”", author: "William James" },
    { text: "“Keep your eyes on the stars, and your feet on the ground.”", author: "Theodore Roosevelt" },
    { text: "“The best time to plant a tree was 20 years ago. The second best time is now.”", author: "Chinese Proverb" },
    { text: "“I find that the harder I work, the more luck I seem to have.”", author: "Thomas Jefferson" },
    { text: "“Don’t count the days, make the days count.”", author: "Muhammad Ali" },
    { text: "“It is during our darkest moments that we must focus to see the light.”", author: "Aristotle" },
    { text: "“The only limit to our realization of tomorrow will be our doubts of today.”", author: "Franklin D. Roosevelt" },
    { text: "“Do what you can, with what you have, where you are.”", author: "Theodore Roosevelt" },
    { text: "“You miss 100% of the shots you don’t take.”", author: "Wayne Gretzky" },
    { text: "“Whether you think you can or you think you can’t, you’re right.”", author: "Henry Ford" },
    { text: "“The mind is everything. What you think you become.”", author: "Buddha" },
    { text: "“The best revenge is massive success.”", author: "Frank Sinatra" },
    { text: "“I have not failed. I’ve just found 10,000 ways that won’t work.”", author: "Thomas Edison" },
    { text: "“You can’t use up creativity. The more you use, the more you have.”", author: "Maya Angelou" },
    { text: "“We may encounter many defeats but we must not be defeated.”", author: "Maya Angelou" },
    { text: "“Alone we can do so little; together we can do so much.”", author: "Helen Keller" },
    { text: "“The only way to have a friend is to be one.”", author: "Ralph Waldo Emerson" },
    { text: "“Logic will get you from A to B. Imagination will take you everywhere.”", author: "Albert Einstein" },
    { text: "“Life is 10% what happens to us and 90% how we react to it.”", author: "Charles R. Swindoll" },
    { text: "“The best and most beautiful things in the world cannot be seen or even touched – they must be felt with the heart.”", author: "Helen Keller" },
    { text: "“Try not to become a man of success, but rather try to become a man of value.”", author: "Albert Einstein" },
    { text: "“The only person you are destined to become is the person you decide to be.”", author: "Ralph Waldo Emerson" },
    { text: "“Go confidently in the direction of your dreams. Live the life you have imagined.”", author: "Henry David Thoreau" },
    { text: "“In the middle of every difficulty lies opportunity.”", author: "Albert Einstein" },
    { text: "“You must be the change you wish to see in the world.”", author: "Mahatma Gandhi" },
    { text: "“An investment in knowledge pays the best interest.”", author: "Benjamin Franklin" },
    { text: "“The roots of education are bitter, but the fruit is sweet.”", author: "Aristotle" },
    { text: "“Education is not preparation for life; education is life itself.”", author: "John Dewey" },
    { text: "“The purpose of education is to replace an empty mind with an open one.”", author: "Malcolm Forbes" },
    { text: "“Develop a passion for learning. If you do, you will never cease to grow.”", author: "Anthony J. D’Angelo" },
    { text: "“Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.”", author: "Abigail Adams" },
    { text: "“The more that you read, the more things you will know. The more that you learn, the more places you’ll go.”", author: "Dr. Seuss" },
    { text: "“Live as if you were to die tomorrow. Learn as if you were to live forever.”", author: "Mahatma Gandhi" },
    { text: "“Wisdom is not a product of schooling but of the lifelong attempt to acquire it.”", author: "Albert Einstein" },
    { text: "“The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.”", author: "Brian Herbert" },
    { text: "“Anyone who stops learning is old, whether at twenty or eighty.”", author: "Henry Ford" },
    { text: "“He who learns but does not think, is lost! He who thinks but does not learn is in great danger.”", author: "Confucius" },
    { text: "“The beautiful thing about learning is nobody can take it away from you.”", author: "B.B. King" },
    { text: "“I am always ready to learn although I do not always like being taught.”", author: "Winston Churchill" },
    { text: "“Tell me and I forget. Teach me and I remember. Involve me and I learn.”", author: "Benjamin Franklin" },
    { text: "“Learning is a treasure that will follow its owner everywhere.”", author: "Chinese Proverb" },
    { text: "“Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing.”", author: "William Arthur Ward" },
    { text: "“Your education is a dress rehearsal for a life that is yours to lead.”", author: "Nora Ephron" },
    { text: "“The difference between school and life? In school, you’re taught a lesson and then given a test. In life, you’re given a test that teaches you a lesson.”", author: "Tom Bodett" },
    { text: "“Education is the key to unlock the golden door of freedom.”", author: "George Washington Carver" },
    { text: "“The goal of education is the advancement of knowledge and the dissemination of truth.”", author: "John F. Kennedy" },
    { text: "“Education is not the filling of a pail, but the lighting of a fire.”", author: "William Butler Yeats" },
    { text: "“A person who won’t read has no advantage over one who can’t read.”", author: "Mark Twain" },
    { text: "“Education is the passport to the future, for tomorrow belongs to those who prepare for it today.”", author: "Malcolm X" },
    { text: "“Learning never exhausts the mind.”", author: "Leonardo da Vinci" },
    { text: "“I have never let my schooling interfere with my education.”", author: "Mark Twain" },
    { text: "“The mind once enlightened cannot again become dark.”", author: "Thomas Paine" },
    { text: "“Formal education will make you a living; self‑education will make you a fortune.”", author: "Jim Rohn" },
    { text: "“The whole purpose of education is to turn mirrors into windows.”", author: "Sydney J. Harris" },
    { text: "“Education is what remains after one has forgotten what one has learned in school.”", author: "Albert Einstein" },
    { text: "“It is not that I’m so smart. But I stay with the questions much longer.”", author: "Albert Einstein" },
    { text: "“Wonder is the beginning of wisdom.”", author: "Socrates" },
    { text: "“Knowledge speaks, but wisdom listens.”", author: "Jimi Hendrix" },
    { text: "“The only true wisdom is in knowing you know nothing.”", author: "Socrates" },
    { text: "“By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.”", author: "Confucius" },
    { text: "“It is the mark of an educated mind to be able to entertain a thought without accepting it.”", author: "Aristotle" },
    { text: "“Education is the ability to listen to almost anything without losing your temper or your self‑confidence.”", author: "Robert Frost" },
    { text: "“The test and the use of man’s education is that he finds pleasure in the exercise of his mind.”", author: "Jacques Barzun" },
    { text: "“The direction in which education starts a man will determine his future in life.”", author: "Plato" },
    { text: "“Education breeds confidence. Confidence breeds hope. Hope breeds peace.”", author: "Confucius" }
  ],

  // Study tips
  studyTips: [
    "Create a study timetable and stick to it.",
    "Use active recall: test yourself instead of just re‑reading.",
    "Teach someone else – it reinforces your understanding.",
    "Take regular breaks: the Pomodoro technique (25 min study, 5 min break).",
    "Use mnemonics and acronyms to remember lists.",
    "Do past exam papers under timed conditions.",
    "Keep a dedicated study space free from distractions.",
    "Get enough sleep – it helps memory consolidation.",
    "Stay hydrated and eat brain‑boosting foods (nuts, fruits).",
    "Break large topics into smaller, manageable chunks.",
    "Review your notes within 24 hours of learning them.",
    "Summarise each topic in your own words.",
    "Draw diagrams and mind maps – visual learning aids.",
    "Set specific, measurable goals for each study session.",
    "Eliminate phone distractions: put it in another room or use apps to block social media.",
    "Start with the hardest subject first when your mind is fresh.",
    "Reward yourself after completing a task or study block.",
    "Study with a group: discuss and quiz each other.",
    "Use flashcards (physical or digital like Anki) for memorisation.",
    "Read the syllabus and learning objectives so you know what is expected.",
    "Practise writing essays under exam conditions to improve speed and structure.",
    "Listen to instrumental music or white noise if it helps you concentrate.",
    "Keep a ‘mistake journal’ – write down questions you got wrong and revisit them.",
    "Vary your study methods: reading, writing, speaking, listening.",
    "Use online resources like Khan Academy, YouTube, and PhET simulations.",
    "Don’t just memorise facts – understand concepts and how to apply them.",
    "Take handwritten notes – it improves retention better than typing.",
    "Stay organised: keep separate notebooks or folders for each subject.",
    "Review at the end of each week what you’ve learned.",
    "Don’t cram: spaced repetition over time is far more effective.",
    "Get a study buddy and keep each other accountable.",
    "When you’re tired, switch to a lighter task or take a power nap.",
    "Use colour‑coding in your notes to highlight key points.",
    "Attend all classes (in person or online) and participate actively.",
    "Don’t be afraid to ask teachers or classmates for help.",
    "Take care of your mental health: exercise, meditate, and take time off.",
    "Avoid multitasking – focus on one subject at a time.",
    "Create a cheat sheet of formulas and key facts for quick revision.",
    "Regularly test yourself with flashcards or friends.",
    "After reading a paragraph, close the book and try to recall the key points.",
    "Use the Feynman technique: explain a concept as if teaching a child.",
    "Chunk similar topics together when studying to build connections.",
    "Don’t study in bed – your brain should associate bed with sleep, not work.",
    "Keep a positive mindset: remind yourself why you’re studying.",
    "Write down questions you have while studying and find answers later.",
    "Use past papers to identify common question patterns.",
    "Highlight only key words – avoid over‑highlighting.",
    "Take a 5‑minute walk between study sessions to refresh your brain.",
    "Create a study playlist that you only listen to while studying – it becomes a concentration trigger.",
    "Plan your week every Sunday evening.",
    "Set a timer for each task to create a sense of urgency.",
    "Review the hardest topics more frequently.",
    "Don’t compare your progress to others; focus on your own improvement.",
    "Keep a growth mindset: mistakes are opportunities to learn.",
    "Stay consistent – even 30 minutes a day adds up.",
    "Use analogies to relate new information to something you already know.",
    "Recite information aloud – hearing your own voice reinforces memory.",
    "Visualise success in your exams to boost confidence.",
    "Practise deep breathing if you feel anxious before or during study.",
    "Rotate subjects to keep your brain engaged.",
    "Write practice questions for yourself and answer them later.",
    "Use the Leitner system for flashcards (sort by how well you know them).",
    "Keep a water bottle at your desk – dehydration affects concentration.",
    "Review the learning objectives before each chapter.",
    "Use apps like Forest or Focusmate to stay on task.",
    "Set up a reward system: e.g., watch an episode after 2 hours of study.",
    "Read the question carefully before answering – many marks are lost by misreading.",
    "Show all your working – you may get partial credit even if the final answer is wrong.",
    "Check your answers if you have time at the end of an exam.",
    "Underline command words in questions: describe, explain, evaluate, compare.",
    "Plan your essay before writing – a quick outline saves time and improves structure.",
    "If stuck on a question, move on and come back later.",
    "Use the marks as a guide to how much detail is needed.",
    "Eat a good breakfast on exam day – your brain needs energy.",
    "Arrive early to the exam venue so you can relax.",
    "Read all instructions on the cover page before starting.",
    "Bring spare pens, pencils, and a watch (if allowed).",
    "Stay calm – take a few deep breaths if you panic.",
    "Celebrate your effort, not just the outcome – every study session counts."
  ],

  // Pre‑loaded discussion threads
  discussions: [
    {
      topic: "How do you memorise formulas effectively?",
      replies: [
        "I write them on sticky notes and stick them around my room where I see them daily.",
        "Flashcards saved me – I use the Anki app to review formulas every day.",
        "I try to understand the logic behind the formula instead of rote memorisation.",
        "Creating a formula sheet and reviewing it every morning helps me a lot.",
        "I make up stories or acronyms to remember sequences of formulas.",
        "Practising problems that use the formula solidifies it in my mind.",
        "I record myself saying the formula aloud and listen to it before bed."
      ]
    },
    {
      topic: "What is the best way to prepare for LGCSE English?",
      replies: [
        "Read widely – newspapers, novels, short stories – to improve comprehension.",
        "Practise writing essays under timed conditions and ask a teacher to mark them.",
        "Learn the common literary devices (simile, metaphor, etc.) and spot them in texts.",
        "Summarise passages in your own words to check understanding.",
        "Do past paper questions and compare your answers with the mark scheme.",
        "Expand your vocabulary – learn 5 new words a day and use them in sentences.",
        "Join a study group where you discuss themes and characters from set books."
      ]
    },
    {
      topic: "How do you stay motivated during long study sessions?",
      replies: [
        "I use the Pomodoro timer: 25 minutes study, 5 minutes break.",
        "I set small goals and tick them off – that feeling of progress keeps me going.",
        "I remind myself of the bigger picture: why I'm studying and what I want to achieve.",
        "Changing my study environment every few hours helps refresh my mind.",
        "I listen to instrumental music or nature sounds.",
        "I reward myself after completing a difficult topic – a snack, a short walk, etc.",
        "Studying with a friend holds me accountable and makes it more enjoyable."
      ]
    },
    {
      topic: "Tips for science practical exams?",
      replies: [
        "Know your apparatus and their uses; practise setting up experiments.",
        "Understand the theory behind each practical – don't just memorise steps.",
        "Learn how to record observations accurately and present data in tables.",
        "Draw graphs carefully: label axes, use appropriate scales, plot points accurately.",
        "Review common sources of error and how to improve accuracy.",
        "Practise writing conclusions and evaluations for experiments.",
        "Watch virtual lab simulations if you can't access a real lab."
      ]
    },
    {
      topic: "How to handle exam anxiety?",
      replies: [
        "Prepare thoroughly – confidence comes from knowing you've put in the work.",
        "Practice relaxation techniques: deep breathing, meditation, or stretching.",
        "Get a good night's sleep before the exam – avoid last‑minute cramming.",
        "Arrive at the exam venue early so you're not rushing.",
        "Read through the entire paper first to calm your nerves and plan your time.",
        "Focus on one question at a time; don't worry about the rest.",
        "Remember that it's normal to feel nervous – it can actually sharpen your focus."
      ]
    },
    {
      topic: "What are your favourite free study resources?",
      replies: [
        "Khan Academy for Math and Science – excellent videos and practice exercises.",
        "BBC Bitesize for English and History – clear, concise notes.",
        "PhET Interactive Simulations for science practicals – fun and visual.",
        "Quizlet for flashcards – you can find pre‑made sets for almost any subject.",
        "Past papers from the Examinations Council of Lesotho (LEC) website.",
        "CK-12 Foundation for free textbooks and adaptive practice.",
        "Sesotho Online Dictionary for translations and language help."
      ]
    },
    {
      topic: "How do you balance school and personal life?",
      replies: [
        "I create a weekly schedule that includes study time, hobbies, and rest.",
        "I use a planner to track assignments and deadlines so nothing creeps up on me.",
        "I set boundaries: no studying after 9 PM, and I take weekends partially off.",
        "I prioritise tasks – urgent and important things come first.",
        "I make time for exercise and socialising – it recharges my brain.",
        "I avoid procrastination by breaking big tasks into tiny steps.",
        "I remind myself that rest is productive – burnout helps no one."
      ]
    }
  ]
};
